name: ci

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: berndinox/hello-knative:latest
          #build-args: |
          #  arg1=value1
          #  arg2=value2
      -
        name: Hello-Knative
        run: echo ${{ steps.docker_build.outputs.digest }}
